# Generated by Django 5.1.2 on 2024-10-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='decorations/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('contacts', models.TextField()),
                ('stamp', models.ImageField(upload_to='stamps/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.TextField(blank=True, null=True)),
                ('delivery_time', models.CharField(max_length=200)),
                ('decoration', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_offers.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_offers.commercialoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_offers.product')),
            ],
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='products',
            field=models.ManyToManyField(through='commercial_offers.OfferProduct', to='commercial_offers.product'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commercialoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial_offers.userprofile'),
        ),
    ]
